#pragma config(Sensor, S1,     touch,          sensorTouch)
#pragma config(Sensor, S2,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Sensor, S3,     light,          sensorLightActive)
#pragma config(Sensor, S4,     sonar,          sensorSONAR)
#pragma config(Motor,  motorA,          Lookingmotor,  tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorB,          leftMotor,    tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorC,          rightMotor,     tmotorNXT, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
task sound(){


		playTone(10, 2);
    wait1Msec(5);
    playTone(900,2);
    wait10Msec(5);
}
}

task main()
{
	startTask(sound);
	repeatUntil (SensorValue[sonar] <24) {
		motor[motorB] = -52;
		motor[motorC] = -50;
	}
	for(int i = 0; i <= 5; i++)  // initialize int 'i' to 0, and run the loop as long as 'i' is less than 3,
		// incrementing 'i' by 1 after each iteration of the loop
	{
		motor[motorB] = -50 + i*10 ;   // run 'rightMotor' at power level 50
		motor[motorC]  = -50 + i*10;   // run 'leftMotor' at power level 50
		wait1Msec(500);          // wait for 3000 milliseconds before continuing.

	}

	stopAllMotors();
}
