#pragma config(Sensor, S1,     color1,         sensorColorNxtFULL)
#pragma config(Sensor, S2,     color2,         sensorColorNxtFULL)
#pragma config(Sensor, S3,     sonar,          sensorSONAR)
#pragma config(Motor,  motorA,          Lookingmotor,  tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorNXT, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(NXT)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

long nLastXmitTimeStamp = nPgmTime;
long nDeltaTime         = 0;

const int kMaxSizeOfMessage = 30;
const int INBOX = 5;

int black1 = 0, black2 = 0, state = 0;

TFileIOResult nBTCmdRdErrorStatus;
int nSizeOfMessage;
ubyte nRcvBuffer[kMaxSizeOfMessage];
string command = "";

task sound(){ // generating tune while active
 while(1==1){
  playTone(10, 2);
  wait1Msec(50);
  playTone(900,2);
  wait10Msec(50);
 }
}

void Sensor(){
 if (SensorValue[S3]<=24) {
  startTask(sound);
  }
 stopTask(sound);
}
void up(){
  while(SensorValue[color2] == BLACKCOLOR || SensorValue[color1] == BLACKCOLOR){
  motor[motorB] = 50;
  motor[motorC] = 50;
  }
}

void right(){
			int state = 0;
      motor[motorB] = 50;
      motor[motorC] = 50;
      wait1Msec(50);
      motor[motorB] = -10;
      motor[motorC] = 50;
      while(true){
       if (state == 0){
        if (SensorValue[color1] == WHITECOLOR){ state = 1; displayCenteredBigTextLine(2, "1");}
       }
       if (state == 1){
        if (SensorValue[color1] == BLACKCOLOR){ state = 2; displayCenteredBigTextLine(2, "2");}
       }
       if (state == 2){ displayCenteredBigTextLine(2, "over"); break;}

      }
}

void left(){
      int state = 0;
  		displayCenteredBigTextLine(2, "LEFT");
      motor[motorB] = 50;
      motor[motorC] = 50;
      wait1Msec(50);
      motor[motorB] = -10;
      motor[motorC] = 50;
      while(true){
       if (state == 0){
        if (SensorValue[color2] == WHITECOLOR){ state = 1; displayCenteredBigTextLine(2, "1");}
       }
       if (state == 1){
        if (SensorValue[color2] == BLACKCOLOR){ state = 2; displayCenteredBigTextLine(2, "2");}
       }
       if (state == 2){ displayCenteredBigTextLine(2, "over"); break;}

      }
}

void down(){
      motor[motorB] = -10;
      motor[motorC] = 50;
      while(true){
       if (state == 0){
        if (SensorValue[color2] == WHITECOLOR){ state = 1; displayCenteredBigTextLine(2, "1");}
       }
       if (state == 1){
        if (SensorValue[color2] == BLACKCOLOR){ state = 2; displayCenteredBigTextLine(2, "2");}
       }
       if (state == 2){
        if (SensorValue[color2] == WHITECOLOR){ state = 3; displayCenteredBigTextLine(2, "2");}
       }
       if (state == 3){
        if (SensorValue[color2] == BLACKCOLOR){ state = 4; displayCenteredBigTextLine(2, "2");}
       }
       if (state == 4){ displayCenteredBigTextLine(2, "over"); break;}
      }
}

void bluetooth(string &s)
{
 nSizeOfMessage = cCmdMessageGetSize(INBOX);
 if (nSizeOfMessage > kMaxSizeOfMessage)
  nSizeOfMessage = kMaxSizeOfMessage;
 if (nSizeOfMessage > 0){
  nBTCmdRdErrorStatus = cCmdMessageRead(nRcvBuffer, nSizeOfMessage, INBOX);
  nRcvBuffer[nSizeOfMessage] = '\0';
  stringFromChars(s, (char *) nRcvBuffer);
  displayCenteredBigTextLine(5, s);
 }
}

// initialising main task
task main(){
 while(true){
  while(true){
   Sensor();
   state = 0;
   switch(SensorValue[color1])
   {
   case BLACKCOLOR:   motor[motorB] = -10;   black1 = 1 ; break; // if black, stop moving
   case WHITECOLOR:  motor[motorB] = 50;  black1 = 0 ;  break; // if white, start driving
   }
   switch(SensorValue[color2])
   {
   case BLACKCOLOR:   motor[motorC] = -10;   black2 = 1 ; break; // same as above
   case WHITECOLOR:  motor[motorC] = 50;  black2 = 0 ; break;
   }

   wait1Msec(50);

   if((black1 == 1) && (black2 == 1)){
    motor[motorB] = 0;
    motor[motorC] = 0;
    int i=0;
    for(i=0; i<5; i++){
     bluetooth(command);
     if (command == "UP"){
     up(); 
     command = "";
     }
     if (command == "LEFT"){
			left();
      command = "";
     }
     if (command == "RIGHT"){
      displayCenteredBigTextLine(2, "RIGHT");
			right();
      command = "";
     }
     if (command == "DOWN"){
      displayCenteredBigTextLine(2, "DOWN");
			down();
      command = "";break;}
       }
      }
     }
     if (command == ""){
      displayCenteredBigTextLine(2, "Niks");
     }
    }
   }